Repository mty22/krunker.io-translations, pull requests merged in 2021-12, with the labels that each got.

#282 Update kr.js
  kr.js
Labels: minor-changes, ready to merge

#284 Update ru.js (TiXoNyA+Yurikan4ik)
  ru.js
Labels: ready to merge

#287 Update Portuguese to v4.2.2
  README.md
  pr.js
  status.txt
Labels: pending-review, ready to merge
