Repository mty22/krunker.io-translations, pull requests merged in 2021-05, with the labels that each got.

#168 Minor edits to kr.js
  kr.js
Labels: minor-changes, pending-review

#79 New Russian translation (v3.8.1)
  ru.js
Labels: help wanted, high-priority, new-language, pending-review

#142 Portuguese Translation (v3.8.1)
  pr.js
Labels: help wanted, high-priority, major-changes, pending-review, work-in-progress

#181 Updated jp.js (v3.8.6)
  jp.js
Labels: help wanted, minor-changes, pending-review

#183 Update kr.js
  kr.js
Labels: minor-changes, pending-review

#182 Updated fr.js
  fr.js
Labels: minor-changes, ready to merge

#184 Update es.js (3.8.6)
  es.js
Labels: minor-changes, ready to merge

#180 Update hi.js (v 3.8.6)
  hi.js
Labels: minor-changes, pending-review, work-in-progress

#173 Added italian translation
  CODEOWNERS
  it.js
Labels: help wanted, new-language, pending-review
