Repository mty22/krunker.io-translations, pull requests merged in 2021-09, with the labels that each got.

#253 Updated jp.js [v4.2.2]
  jp.js
Labels: pending-review, ready to merge

#254 nl.js update v4.2.2
  nl.js
Labels: help wanted, pending-review

#259 Update kr.js (v4.2.2)
  kr.js
Labels: ready to merge

#255 Updated fr.js based on pull 251
  fr.js
Labels: ready to merge

#266 Update pl.js
  README.md
  pl.js
Labels: ready to merge

#261 Update it.js
  it.js
Labels: ready to merge

#260 Update vn.js v4.2.2
  Vietnamese Language
  translate to Vietnamese
Labels: pending-review
