Repository mty22/krunker.io-translations, pull requests merged in 2021-04, with the labels that each got.

#19 Translated new sentences to Japanese
  jp.js
Labels: general-changes

#34 Translated new sentences in jp.js for v3.8.1
  jp.js
Labels: help wanted, minor-changes, pending-review

#93 Added "how to submit a pull request" to README.md
  README.md
Labels: grammar-issues, pending-review

#86 Turkish Create tr.js (v3.8.1)
  tr.js
Labels: new-language, pending-review, ready to merge

#97 Update README.md
  README.md
Labels: grammar-issues

#88 Create nl.js - Dutch (v3.8.1)
  nl.js
Labels: high-priority, new-language, pending-review, ready to merge

#95 Repatch kr.js
  kr.js
Labels: high-priority, minor-changes, pending-review

#77 Update Spanish translation (v3.8.1)
  es.js
Labels: high-priority, minor-changes, pending-review, ready to merge

#102 Updated fr.js | 100% complete
  fr.js
Labels: pending-review

#73 Update de.js
  de.js
Labels: help wanted, minor-changes, pending-review

#24 Polish language support (v3.8.1)
  pl.js
Labels: On Hold, high-priority, new-language, ready to merge

#132 Updated de.js (small update)
  de.js
Labels: minor-changes

#122 25%
  it.js
Labels: On Hold, new-language, work-in-progress

#90 Krunker Croatian Support (cr.js based on v3.8.1)
  cr.js
Labels: help wanted, new-language, pending-review

#91 Add Bulgarian language (non-approved) v3.8.1
  non-approved-languages/README.md
  non-approved-languages/bg.js
  non-approved-languages/non-approved-languages.js
Labels: help wanted, new-language, pending-review, work-in-progress

#94 Slovenian Translation of Krunker
  en.js
  sl.js
Labels: help wanted, pending-review

#130 Update kr.js (v3.8.2)
  CODEOWNERS
  README.md
  kr.js
Labels: help wanted, minor-changes, pending-review

#153 Update de.js(v3.8.2)
  de.js
Labels: minor-changes, pending-review

#131 Updated jp.js(v3.8.2)
  README.md
  jp.js
Labels: minor-changes, question

#156 nl.js - Minor fixes and added new translations. DUTCH (v3.8.2)
  nl.js
Labels: minor-changes, pending-review

#161 jp.js item.sell.quick fix (v3.8.2)
  jp.js
Labels: bug, pending-review

#158 Spanish updates (v3.8.2)
  es.js
Labels: minor-changes, ready to merge

#159 Updated fr.js
  fr.js
Labels: minor-changes, ready to merge

#17 Add Hindi support - v3.8.1
  README.md
  hi.js
Labels: help wanted, high-priority, new-language, pending-review, ready to merge

#164 Spanish Edit (3.8.4)
  es.js
Labels: minor-changes, ready to merge

#162 Updated fr.js
  fr.js
Labels: ready to merge

#104 Update zh.js FINAL VERSION (reviewed by WpyGG) (v3.8.1)
  zh.js
Labels: pending-review, ready to merge
