Repository mty22/krunker.io-translations, pull requests merged in 2021-07, with the labels that each got.

#170 Add Tagalog language
  pending/tagalog.txt
  pending/tg.js
Labels: grammar-issues, minor-changes, new-language, ready to merge

#201 Update pr.js
  pr.js
Labels: minor-changes, pending-review, ready to merge

#178 pl.js update (v3.8.6)
  pl.js
Labels: minor-changes, ready to merge

#193 Updates to ru.js based on v3.8.6 en.js (submitted on behalf of chxrge)
  ru.js
Labels: help wanted, pending-review

#218 Update jp.js (v4.0.9)
  jp.js
Labels: pending-review, ready to merge

#216 Updated fr.js based on en.js v4.0.9
  fr.js
Labels: minor-changes, pending-review

#208 Update es.js
  es.js
Labels: minor-changes, pending-review, ready to merge

#224 [Japanese] Fix Grammer Problem
  README.md
  jp.js
Labels: pending-review, ready to merge

#209 Update kr.js
  kr.js
Labels: pending-review

#226 updated it.js
  it.js
Labels: pending-review
