Repository mty22/krunker.io-translations, pull requests merged in 2021-08, with the labels that each got.

#217 Update zhtr.js (v4.0.9)
  zhtr.js
Labels: help wanted, pending-review

#225 Update pl.js (v4.0.9)
  pl.js
Labels: help wanted, pending-review

#239 Some changes to kr.js (Korean)
  kr.js
Labels: general-changes

#228 Update tr.js (v4.0.9)
  work-in-progress/tr.js
Labels: new-language, work-in-progress

#240 Update tr.js
  tr.js
Labels: work-in-progress

#211 Update tg.js (Tagalog Language based on 4.0.9)
  tg.js
Labels: general-changes, ready to merge

#230 Update hi.js
  hi.js
Labels: pending-review, work-in-progress

#237 Update zhtr.js (v4.1.4)
  zhtr.js
Labels: help wanted, pending-review

#212 Update zh.js (v4.1.4)
  zh.js
Labels: help wanted, pending-review
