Repository mty22/krunker.io-translations, pull requests merged in 2021-10, with the labels that each got.

#252 Update tg.js v4.2.2 (Tagalog)
  tg.js
Labels: help wanted, ready to merge, work-in-progress

#256 Update zh.js (v4.2.2)
  zh.js
Labels: ready to merge

#258 Update zhtr.js (v4.2.2)
  zhtr.js
Labels: ready to merge

#257 Update tr.js
  tr.js
Labels: ready to merge

#236 Update fi.js
  fi.js
Labels: help wanted, high-priority, pending-review

#268 Update ru.sj on behalf of coeg701 (v4.0.9)
  ru.js
Labels: help wanted, high-priority, pending-review
