Repository mty22/krunker.io-translations, pull requests merged in 2022-07, with the labels that each got.

#440 Updates in es.js
  es.js
Labels: ready to merge, size/L

#444 Minor change in hi.js
  hi.js
Labels: ready to merge, size/XS

#446 Update zh.js (Quality bump #2)
  zh.js
Labels: ready to merge, size/M

#458 Combined changes of #444 #448 #449 #451
  hi.js
Labels: size/S

#463 Update sq.js
  work-in-progress/sq.js
Labels: size/XXL

#447 General fixes to es.js
  es.js
Labels: ready to merge, size/L

#464 Update sl.js
  work-in-progress/sl.js
Labels: size/L

#465 Update sl.js
  work-in-progress/sl.js
Labels: size/M

#466 V5.7.0 enjs update
  de.js
  en.js
  es.js
  fi.js
  fr.js
  hi.js
  it.js
  jp.js
  kr.js
  nl.js
  pl.js
  pr.js
  ru.js
  tg.js
  tr.js
  work-in-progress/bg.js
  work-in-progress/bn.js
  work-in-progress/cr.js
  work-in-progress/hu.js
  work-in-progress/ma.js
  work-in-progress/sl.js
  work-in-progress/sq.js
  work-in-progress/vn.js
  zh.js
  zhtr.js
Labels: size/XL

#485 Update CODEOWNERS (es.js)
  CODEOWNERS
Labels: size/XS

#491 Reversion
  work-in-progress/sl.js
  work-in-progress/slovenian.txt
  work-in-progress/sq.js
Labels: size/XXL
