Repository mty22/krunker.io-translations, pull requests merged in 2022-02, with the labels that each got.

#313 bg.js
  work-in-progress/bg.js
Labels: size/L

#298 hi.js update for v5.4.1
  hi.js
Labels: ready to merge, size/L

#309 french translation update
  fr.js
Labels: pending-review, ready to merge, size/L

#310 Update nl.js changes 2/2/2022
  nl.js
Labels: ready to merge, size/M

#312 translated the challenges for tr.js
  tr.js
Labels: pending-review, ready to merge, size/M

#311 Update 2 pr.js Portuguese based on en.js (v5.4.2)
  pr.js
Labels: pending-review, ready to merge, size/L

#321 Update bluzeds name
  CONTRIBUTORS.md
Labels: size/XS

#322 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: size/XS

#297 [Change] Japanese - Updates for v5.4.1
  jp.js
Labels: ready to merge, size/M

#302 New translations for it.js
  it.js
Labels: ready to merge, size/L

#303 Update kr.js (v5.4.1)
  kr.js
Labels: ready to merge, size/L

#334 Update ru.js on behalf of TiXoNyA
  ru.js
Labels: ready to merge, size/L

#304 Update de.js based on en.js (v5.4.1)
  de.js
Labels: pending-review, ready to merge, size/L

#295 Update es.js
  es.js
Labels: ready to merge, size/L

#335 Fix tg.js (original PR #299)
  CODEOWNERS
  tg.js
Labels: pending-review, size/L

#274 Update languages.js to represent actual languages (0v0katai's changes)
  languages.js
Labels: pending-review, Escalated

#342 Fix typo in contributors hyperlink
  README.md
Labels: size/XS

#341 Remove @apinklover from Korean translators
  CODEOWNERS
Labels: size/XS

#336 Update pl.js
  pl.js
Labels: ready to merge, size/L

#318 Update zh.js & zhtr.js (v5.4.2)
  zh.js
  zhtr.js
Labels: pending-review, size/XL

#331 update tr.js
  tr.js
Labels: pending-review, size/L

#327 [WIP] bg.js
  work-in-progress/bg.js
Labels: work-in-progress, size/XL

#333 [WIP] New bn.js (v5.4.2)
  work-in-progress/bn.js
Labels: work-in-progress, size/XL

#344 Rewind of 2 lines in pl.js
  pl.js
Labels: size/XS

#346 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: size/XS

#343 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: size/XS

#348 en.js updates v5.4.4
  de.js
  en.js
  es.js
  fi.js
  fr.js
  hi.js
  it.js
  jp.js
  kr.js
  nl.js
  pl.js
  pr.js
  ru.js
  status.txt
  tg.js
  tr.js
  work-in-progress/bg.js
  work-in-progress/bn.js
  work-in-progress/cr.js
  work-in-progress/hu.js
  work-in-progress/sl.js
  work-in-progress/sq.js
  work-in-progress/vn.js
  zh.js
  zhtr.js
Labels: size/XXL

#354 Fix commands.spraybypass.* wording (v5.4.4)
  en.js
  work-in-progress/bg.js
  work-in-progress/bn.js
  work-in-progress/cr.js
  work-in-progress/hu.js
  work-in-progress/sl.js
  work-in-progress/sq.js
  work-in-progress/vn.js
Labels: size/M

#339 Update hi.js
  hi.js
Labels: ready to merge, size/S

#353 Update kr.js
  kr.js
Labels: ready to merge, size/L

#355 Update pl.js
  pl.js
Labels: ready to merge, size/L

#356 Changes for v5.4.4(Japanese)
  jp.js
Labels: pending-review, ready to merge, size/M

#357 hi.js update as per v5.4.4
  hi.js
Labels: ready to merge, size/L

#359 Update tr.js
  tr.js
Labels: ready to merge, size/L

#345 Update fi.js
  fi.js
Labels: ready to merge, size/XL

#360 Update tg.js
  tg.js
Labels: ready to merge, size/L

#362 update nl.js v5.4.4
  nl.js
Labels: ready to merge, size/L

#365 [WIP] Malayalam - ma.js
  work-in-progress/ma.js
Labels: size/XL

#367 Update CONTRIBUTROS.md
  CONTRIBUTORS.md
Labels: size/XS

#369 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: size/XS

#371 ma.js
  work-in-progress/ma.js
Labels: size/L

#370 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: size/XS

#358 Update de.js
  de.js
Labels: pending-review, size/L

#366 Update es.js
  es.js
Labels: pending-review, ready to merge, size/L

#361 Update zh.js & zhtr.js (v5.4.4)
  zh.js
  zhtr.js
Labels: ready to merge, size/L
