Repository mty22/krunker.io-translations, pull requests merged in 2022-05, with the labels that each got.

#350 Update pr.js with en.js updates (v5.4.4)
  pr.js
Labels: high-priority, pending-review, ready to merge, size/L

#384 Update de.js
  de.js
Labels: ready to merge, size/S

#385 Update fi.js
  fi.js
Labels: high-priority, ready to merge, size/L

#411 Update nl.js
  nl.js
Labels: ready to merge, size/S

#424 Major changes in pl.js
  CONTRIBUTORS.md
  pl.js
Labels: ready to merge, size/L

#428 Update zh.js & zhtr.js (Quality bump, v5.4.2)
  zh.js
  zhtr.js
Labels: ready to merge, size/XL

#407 Changes to Japanese v5.4.2.
  CONTRIBUTORS.md
  jp.js
Labels: pending-review, size/L

#441 Discord tag/discriminator update
  CONTRIBUTORS.md
Labels: size/XS

#390 Update fr.js
  fr.js
Labels: pending-review, size/L
