Repository mty22/krunker.io-translations, pull requests merged in 2022-09, with the labels that each got.

#467 small fixes to jp.js
  CONTRIBUTORS.md
  jp.js
Labels: ready to merge, size/M

#469 Update kr.js (v5.7.0)
  kr.js
Labels: ready to merge, size/M

#478 Update zhtr.js (v5.7.0)
  zhtr.js
Labels: ready to merge, size/L

#488 Updated de.js based on en.js (v5.7.0)
  CODEOWNERS
  de.js
Labels: size/M

#470 tg.js - Update 5.7.0
  tg.js
Labels: size/L

#480 Update pl.js (v5.7.0)
  CODEOWNERS
  pl.js
Labels: size/M

#497 Updated nl.js based on en.js
  nl.js
Labels: pending-review, size/M
