Repository mty22/krunker.io-translations, pull requests merged in 2022-04, with the labels that each got.

#375 hi.js changes
  hi.js
Labels: ready to merge, size/S

#377 Changes and fixes for v5.4.2(Japanese)
  jp.js
Labels: ready to merge, size/L

#378 Update kr.js
  kr.js
Labels: ready to merge, size/S

#410 Syntactical changes to players joining and leaving
  kr.js
Labels: grammar-issues, ready to merge, size/XS

#380 Completing hungarian
  work-in-progress/hu.js
Labels: size/XL

#425 Updated my contact info
  CONTRIBUTORS.md
Labels: size/XS
